<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/themes/wh40k.min.css')) ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/themes/jquery.mobile.icons.min.css')) ?>
        <?php echo $this->headLink()->appendStylesheet('http://code.jquery.com/mobile/1.4.5/jquery.mobile.structure-1.4.5.min.css') ?>
        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/my_style.css')) ?>
        <link rel="icon" type="image/png" href="<?php echo $this->baseUrl('/images/icons/favicon4.png'); ?>"/>
        <script src="<?php echo $this->baseUrl('/js/submitFormat.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/datePicker.js'); ?>"></script>
        <title>Warhammer 40k Tools</title>
  <meta charset="utf-8">
  <title>jQuery UI Datepicker - Display month &amp; year menus</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
        
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="<?php echo $this->baseUrl('/js/datePicker.js'); ?>"></script>
</head>
<body>
        <div id="background">
            <div id="banner_div">
                <img id="banner" src="<?php echo $this->baseUrl('/images/banner.jpg'); ?>"/>
            </div>
            <div id="menuWrapper">
                
            </div>
        </div>  
    </body>
 
 
</body>
</html>